In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [5]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [6]:
df.Message.unique()

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       ..., 'Pity, * was in mood for that. So...any other suggestions?',
       "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free",
       'Rofl. Its true to its name'], dtype=object)

In [7]:
df['spam']= df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [8]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [13]:
df.drop('Category', axis='columns')

Message  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568               Will ü b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [14]:
from sklearn.model_selection import train_test_split

X_train , X_test, y_train, y_test=train_test_split(df.Message, df.spam, test_size=0.2 )

In [16]:
X_train.shape

(4457,)

In [18]:
X_test.shape

(1115,)

In [20]:
type(X_train)

pandas.core.series.Series

In [21]:
X_train[:3]

C:\Users\MY PC\AppData\Local\Temp\ipykernel_5620\1529872051.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  X_train[:3]


495                      Are you free now?can i call now?
4697    A guy who gets used but is too dumb to realize...
3015       I might go 2 sch. Yar at e salon now v boring.
Name: Message, dtype: object

In [22]:
X_train.values

array(['Are you free now?can i call now?',
       'A guy who gets used but is too dumb to realize it.',
       'I might go 2 sch. Yar at e salon now v boring.', ...,
       "Hiya. How was last night? I've been naughty and bought myself clothes and very little ... Ready for more shopping tho! What kind of time do you wanna meet?",
       'Funny fact Nobody teaches volcanoes 2 erupt, tsunamis 2 arise, hurricanes 2 sway aroundn no 1 teaches hw 2 choose a wife Natural disasters just happens',
       'Went to pay rent. So i had to go to the bank to authorise the payment.'],
      dtype=object)

In [23]:
type(X_train.values)

numpy.ndarray

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

v= CountVectorizer()
X_train_cv= v.fit_transform(X_train.values)
X_train_cv
    

<4457x7771 sparse matrix of type '<class 'numpy.int64'>'
	with 59363 stored elements in Compressed Sparse Row format>

In [25]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
X_train_cv.shape

(4457, 7771)

In [30]:
#to see some words inside the created vocabulary
v.get_feature_names_out()[1000:1030]

array(['anywhere', 'aom', 'apart', 'apartment', 'apes', 'apeshit',
       'aphex', 'apnt', 'apo', 'apologetic', 'apologise', 'apologize',
       'apology', 'app', 'apparently', 'appeal', 'appear', 'appendix',
       'applebees', 'apples', 'application', 'apply', 'applying',
       'appointment', 'appointments', 'appreciate', 'appreciated',
       'approaching', 'appropriate', 'approved'], dtype=object)

In [31]:
v.get_feature_names_out().shape

(7771,)

In [32]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [33]:
v.vocabulary_

{'are': 1042,
 'you': 7733,
 'free': 2967,
 'now': 4859,
 'can': 1623,
 'call': 1598,
 'guy': 3265,
 'who': 7519,
 'gets': 3107,
 'used': 7244,
 'but': 1567,
 'is': 3747,
 'too': 7003,
 'dumb': 2485,
 'to': 6962,
 'realize': 5625,
 'it': 3759,
 'might': 4483,
 'go': 3146,
 'sch': 5960,
 'yar': 7701,
 'at': 1111,
 'salon': 5913,
 'boring': 1432,
 'smsservices': 6291,
 'for': 2922,
 'yourinclusive': 7740,
 'text': 6809,
 'credits': 2072,
 'pls': 5272,
 'goto': 3191,
 'www': 7669,
 'comuk': 1943,
 'net': 4755,
 'login': 4193,
 '3qxj9': 470,
 'unsubscribe': 7203,
 'with': 7572,
 'stop': 6520,
 'no': 4811,
 'extra': 2722,
 'charge': 1727,
 'help': 3388,
 '08702840625': 85,
 '220': 360,
 'cm2': 1862,
 '9ae': 736,
 'going': 3158,
 'out': 5031,
 'buy': 1572,
 'mum': 4655,
 'present': 5408,
 'ar': 1037,
 'excellent': 2682,
 'spent': 6401,
 'lt': 4265,
 'gt': 3244,
 'years': 7711,
 'in': 3640,
 'the': 6837,
 'air': 881,
 'force': 2923,
 'iraq': 3740,
 'and': 956,
 'afghanistan': 844,
 'am': 931,

In [34]:
v.get_feature_names_out()[3312]

'happen'

In [35]:
X_train_np=X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
import numpy as np
np.where(X_train_np[0]!=0)

(array([1042, 1598, 1623, 2967, 4859, 7733], dtype=int64),)

In [43]:
from sklearn.naive_bayes import MultinomialNB

model= MultinomialNB()

model.fit(X_train_cv, y_train)

MultinomialNB()

In [44]:
X_test_cv= v.transform(X_test)

In [46]:
model.score(X_test_cv, y_test)

0.9856502242152466

In [49]:
from sklearn.metrics import classification_report

y_pred= model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       951
           1       0.99      0.91      0.95       164

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [50]:
emails = [
    'Hey Mari, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count= v.transform(emails)
model.predict(emails_count)


array([0, 1], dtype=int64)

In [51]:
from sklearn.pipeline import Pipeline

clf= Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [52]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [53]:
print(classification_report(y_test, clf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       951
           1       0.99      0.91      0.95       164

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

