In [1]:
import gensim.downloader as api

wv= api.load("word2vec-google-news-300")

In [5]:
wv["great"]

array([ 7.17773438e-02,  2.08007812e-01, -2.84423828e-02,  1.78710938e-01,
        1.32812500e-01, -9.96093750e-02,  9.61914062e-02, -1.16699219e-01,
       -8.54492188e-03,  1.48437500e-01, -3.34472656e-02, -1.85546875e-01,
        4.10156250e-02, -8.98437500e-02,  2.17285156e-02,  6.93359375e-02,
        1.80664062e-01,  2.22656250e-01, -1.00585938e-01, -6.93359375e-02,
        1.04427338e-04,  1.60156250e-01,  4.07714844e-02,  7.37304688e-02,
        1.53320312e-01,  6.78710938e-02, -1.03027344e-01,  4.17480469e-02,
        4.27246094e-02, -1.10351562e-01, -6.68945312e-02,  4.19921875e-02,
        2.50000000e-01,  2.12890625e-01,  1.59179688e-01,  1.44653320e-02,
       -4.88281250e-02,  1.39770508e-02,  3.55529785e-03,  2.09960938e-01,
        1.52343750e-01, -7.32421875e-02,  2.16796875e-01, -5.76171875e-02,
       -2.84423828e-02, -3.60107422e-03,  1.52343750e-01, -2.63671875e-02,
        2.13623047e-02, -1.51367188e-01,  1.04003906e-01,  3.18359375e-01,
       -1.85546875e-01,  

In [6]:
import pandas as pd
df= pd.read_csv("Fake_Real_Data.csv")
df

Text label
0      Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1     U.S. conservative leader optimistic of common ...  Real
2     Trump proposes U.S. tax overhaul, stirs concer...  Real
3      Court Forces Ohio To Allow Millions Of Illega...  Fake
4     Democrats say Trump agrees to work on immigrat...  Real
...                                                 ...   ...
9895   Wikileaks Admits To Screwing Up IMMENSELY Wit...  Fake
9896  Trump consults Republican senators on Fed chie...  Real
9897  Trump lawyers say judge lacks jurisdiction for...  Real
9898   WATCH: Right-Wing Pastor Falsely Credits Trum...  Fake
9899   Sean Spicer HILARIOUSLY Branded As Chickensh*...  Fake

[9900 rows x 2 columns]

In [3]:
df.label.value_counts()

Fake    5000
Real    4900
Name: label, dtype: int64

In [7]:
df['label_num']=df.label.map({"Fake":0, "Real":1})

In [8]:
df

Text label  label_num
0      Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0
1     U.S. conservative leader optimistic of common ...  Real          1
2     Trump proposes U.S. tax overhaul, stirs concer...  Real          1
3      Court Forces Ohio To Allow Millions Of Illega...  Fake          0
4     Democrats say Trump agrees to work on immigrat...  Real          1
...                                                 ...   ...        ...
9895   Wikileaks Admits To Screwing Up IMMENSELY Wit...  Fake          0
9896  Trump consults Republican senators on Fed chie...  Real          1
9897  Trump lawyers say judge lacks jurisdiction for...  Real          1
9898   WATCH: Right-Wing Pastor Falsely Credits Trum...  Fake          0
9899   Sean Spicer HILARIOUSLY Branded As Chickensh*...  Fake          0

[9900 rows x 3 columns]

In [10]:
import spacy

nlp= spacy.load("en_core_web_lg")


In [16]:
def preprocess_and_vectorize(text):
    doc= nlp(text)
    filtered_words=[]
    for token in doc:
        if token.is_punct or token.is_stop:
            continue
        filtered_words.append(token.lemma_)
    return wv.get_mean_vector(filtered_words)

In [11]:
preprocess_and_vectorize("Don't worry if you don't understand that!")

['worry', 'understand']

In [14]:
wv.get_mean_vector(["worry", "understand"], pre_normalize=False)[:3]

array([ 0.00976562, -0.00561523, -0.08905029], dtype=float32)

In [ ]:
worry-> []
understand-> []
average-> [] (300): sentence embeddings

In [15]:
v1=wv["worry"]
v2=wv["understand"]
import numpy as np
np.mean([v1, v2], axis=0)[:3]

array([ 0.00976562, -0.00561523, -0.08905029], dtype=float32)

In [17]:
df['vector']= df['Text'].apply(lambda text: preprocess_and_vectorize(text))

In [18]:
df.head()

Text label  label_num  \
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0   
1  U.S. conservative leader optimistic of common ...  Real          1   
2  Trump proposes U.S. tax overhaul, stirs concer...  Real          1   
3   Court Forces Ohio To Allow Millions Of Illega...  Fake          0   
4  Democrats say Trump agrees to work on immigrat...  Real          1   

                                              vector  
0  [0.008657642, 0.019024342, -0.011917442, 0.032...  
1  [0.010864096, 0.007960429, 0.0011915653, 0.014...  
2  [0.018134918, 0.0062743523, -0.005872244, 0.03...  
3  [0.01255197, 0.012613623, 5.9780963e-05, 0.021...  
4  [-0.0019059887, 0.011889367, 0.0035395357, 0.0...

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(df.vector, df.label_num, test_size=0.2, random_state=2022, stratify= df.label_num)

In [23]:
print("Shape of X_train before reshaping: ", X_train.shape)
print("Shape of X_test before reshaping: ", X_test.shape)

X_train_2d= np.stack(X_train)
X_test_2d= np.stack(X_test)

print("Shape of X_train after reshaping: ", X_train_2d.shape)
print("Shape of X_test after reshaping: ", X_test_2d.shape)

Shape of X_train before reshaping:  (7920,)
Shape of X_test before reshaping:  (1980,)
Shape of X_train after reshaping:  (7920, 300)
Shape of X_test after reshaping:  (1980, 300)


In [26]:
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.metrics import classification_report

clf= HistGradientBoostingRegressor()
#2. fit with all_train_embeddings and y_train
clf.fit(X_train_2d, y_train)


#3. get the predictions for all_test_embeddings and store it in y_pred
y_pred = clf.predict(X_test_2d)


#4. print the classfication report
print(classification_report(y_test, y_pred))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [25]:
test_news = [
    "Michigan governor denies misleading U.S. House on Flint water (Reuters) - Michigan Governor Rick Snyder denied Thursday that he had misled a U.S. House of Representatives committee last year over testimony on Flint’s water crisis after lawmakers asked if his testimony had been contradicted by a witness in a court hearing. The House Oversight and Government Reform Committee wrote Snyder earlier Thursday asking him about published reports that one of his aides, Harvey Hollins, testified in a court hearing last week in Michigan that he had notified Snyder of an outbreak of Legionnaires’ disease linked to the Flint water crisis in December 2015, rather than 2016 as Snyder had testified. “My testimony was truthful and I stand by it,” Snyder told the committee in a letter, adding that his office has provided tens of thousands of pages of records to the committee and would continue to cooperate fully.  Last week, prosecutors in Michigan said Dr. Eden Wells, the state’s chief medical executive who already faced lesser charges, would become the sixth current or former official to face involuntary manslaughter charges in connection with the crisis. The charges stem from more than 80 cases of Legionnaires’ disease and at least 12 deaths that were believed to be linked to the water in Flint after the city switched its source from Lake Huron to the Flint River in April 2014. Wells was among six current and former Michigan and Flint officials charged in June. The other five, including Michigan Health and Human Services Director Nick Lyon, were charged at the time with involuntary manslaughter",
    " WATCH: Fox News Host Loses Her Sh*t, Says Investigating Russia For Hacking Our Election Is Unpatriotic This woman is insane.In an incredibly disrespectful rant against President Obama and anyone else who supports investigating Russian interference in our election, Fox News host Jeanine Pirro said that anybody who is against Donald Trump is anti-American. Look, it s time to take sides,  she began.",
    " Sarah Palin Celebrates After White Man Who Pulled Gun On Black Protesters Goes Unpunished (VIDEO) Sarah Palin, one of the nigh-innumerable  deplorables  in Donald Trump s  basket,  almost outdid herself in terms of horribleness on Friday."
]

test_news_vect=[preprocess_and_vectorize(n) for n in test_news]
clf.predict(test_news_vect)

NameError: name 'clf' is not defined

In [21]:
#finally print the confusion matrix for the best model (GradientBoostingClassifier)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


from matplotlib import pyplot as plt
import seaborn as sn
plt.figure(figsize = (10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Prediction')
plt.ylabel('Truth')

NameError: name 'y_test' is not defined